name: Check Coverage

on: [push]

jobs:
  run-test:
    name: Check Code Coverage on Python 3.7 and ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: git pull submodules
        run: git submodule update --init --recursive

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: install lcov
        run: sudo apt-get install lcov

      - name: Install Ninja for Linux
        run: |
          curl -LO https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-linux.zip
          sudo unzip ninja-linux.zip -d /usr/local/bin/

      - name: Set up CMake
        run: |
          mkdir build
          cd build
          cmake .. -DBUILD_TEST=ON -DBUILD_COV=ON -DCMAKE_BUILD_TYPE=Debug -GNinja

      - name: Build C++ and Run C++ Tests
        run: |
          cd build
          ninja
          ./run-test

      - name: Install Python Dependencies and Package
        run: |
          cd extensions/python
          python -m pip install --upgrade pip
          pip install pytest pytest-cov codecov
          BUILD_COVERAGE=ON python setup.py develop

      - name: Run Python Tests
        run: |
          cd extensions/python
          pytest -v --cov mecab --cov-report=xml

      - name: Report code coverage in .
        run: |
          cd build
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '**/usr/**' '**/tests/**' '**/third_party/**' --output-file coverage.info
          lcov --list coverage.info
          codecov -f coverage.info -F "Cpp" -b ${GITHUB_REF#refs/heads/}

      - name: Report code coverage in extensions/python
        run: |
          cd extensions/python
          codecov -f coverage.xml -Xgcov -F "Python" -b ${GITHUB_REF#refs/heads/}

          cd build
          lcov --directory . --capture --output-file coverage.info
          lcov --remove coverage.info '**/usr/**' '**/tests/**' '**/third_party/**' --output-file coverage.info
          lcov --list coverage.info
          codecov -f coverage.info -Xgcov -F "PythonExtension" -b ${GITHUB_REF#refs/heads/}
